import { mkdir,readFile,writeFile,cp } from 'node:fs/promises';
const assets={};
for(const name of ['index.html','style.css','app.js','admin.html','admin.js','classes.js'])assets['/'+name]=await readFile(new URL('../public/'+name,import.meta.url),'utf8');
const classes=assets['/classes.js'];
const admin=(await readFile(new URL('../worker/admin.js',import.meta.url),'utf8')).replace(/^import .*;\r?\n/gm,'');
const worker=(await readFile(new URL('../worker/index.js',import.meta.url),'utf8')).replace(/^import .*;\r?\n/gm,'');
await mkdir('dist/server',{recursive:true});
await mkdir('dist/.openai',{recursive:true});
await writeFile('dist/server/index.js',classes+'\n'+admin+'\n'+worker+'\nexport default createWorker('+JSON.stringify(assets)+');\n');
await cp('.openai/hosting.json','dist/.openai/hosting.json');
await cp('drizzle','dist/.openai/drizzle',{recursive:true});
console.log('Worker, website en databankmigratie gebouwd.');
